version: '3'
services:
  server:
    build:
      context: .
    command: yarn start:watch
    container_name: api_whatsapp
    env_file: .env
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - './src:/app/src'
      - './nest-cli.json:/app/nest-cli.json'
      - './nodemon.json:/app/nodemon.json'
      - './tsconfig.json:/app/tsconfig.json'
      - './tsconfig.build.json:/app/tsconfig.build.json'
